all: html

SPHINX_PROJECT_NAME = Display Controller Demo Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../../app_display_controller_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
