SPHINX_PROJECT_NAME=Display Controller
VERSION=1.0
DOXYGEN_DIRS= ../app_graphics_demo/src 
SOURCE_INCLUDE_DIRS= ../app_graphics_demo/src 
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
