SPHINX_PROJECT_NAME=Display Controller
VERSION=1.0
DOXYGEN_DIRS= ../module_display_controller/src 
SOURCE_INCLUDE_DIRS= ../module_display_controller/src 
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
