#ifndef _lcd_sdram_manager_internal_h_
#define _lcd_sdram_manager_internal_h_

enum Server_Command {
	CMD_WRITE_LINE_NONBLOCKING,
	CMD_WRITE_LINE_BLOCKING,
	CMD_READ_LINE_NONBLOCKING,
	CMD_READ_LINE_BLOCKING,
	CMD_READ_PARTIAL_LINE_NONBLOCKING,
	CMD_READ_PARTIAL_LINE_BLOCKING,
	CMD_SDRAM_WAIT_UNTIL_IDLE,
	CMD_SET_FRAME_BUFFER,
  CMD_REGISTER_IMAGE
};
#endif
