SPHINX_PROJECT_NAME=ZLG Graphics Display
VERSION=1.0
DOXYGEN_DIRS= ../app_zlg_mtx110e16_demo_2/src ../module_lcd/src ../module_sdram_burst_new/src
SOURCE_INCLUDE_DIRS= ../app_zlg_mtx110e16_demo_2/src ../module_lcd/src ../module_sdram_burst_new/src
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc