all: html

SPHINX_PROJECT_NAME = Display Spectrum from ADC Demo Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../../app_display_spectrum_from_adc
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
